name: 🐛 Bug Report
description: Report a bug or unexpected behavior in AI Site Generator
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report

        Thank you for reporting a bug! Please provide detailed information to help us reproduce and fix the issue.

  - type: checkboxes
    id: preliminary-checks
    attributes:
      label: 🔍 Preliminary Checks
      description: Please confirm you've done these basic checks
      options:
        - label: I've searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I'm using the latest version of AI Site Generator
          required: true
        - label: I've tested in multiple browsers (if applicable)
          required: false

  - type: textarea
    id: bug-description
    attributes:
      label: 📝 Bug Description
      description: Clear and concise description of the bug
      placeholder: Describe what happened vs what you expected
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 🔄 Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected Behavior
      description: What should have happened instead?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: 🌐 Browser
      description: Which browser(s) are affected?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Opera
        - Other
    validations:
      required: true

  - type: dropdown
    id: device-type
    attributes:
      label: 📱 Device Type
      description: What type of device are you using?
      options:
        - Desktop
        - Mobile
        - Tablet
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: 💻 Operating System
      description: Your operating system (e.g., Windows 11, macOS 13, Ubuntu 22.04)
      placeholder: e.g., Windows 11
    validations:
      required: true

  - type: textarea
    id: console-errors
    attributes:
      label: 🔴 Console Errors
      description: Any errors in the browser console (F12 → Console tab)
      placeholder: Paste any console errors here
      render: text

  - type: textarea
    id: additional-context
    attributes:
      label: 📋 Additional Context
      description: Screenshots, network requests, or other relevant information
      placeholder: Add any screenshots, links, or additional context

  - type: checkboxes
    id: severity
    attributes:
      label: ⚠️ Severity
      description: How severe is this bug?
      options:
        - label: Critical - Application is unusable
        - label: High - Major feature is broken
        - label: Medium - Minor feature issue
        - label: Low - UI/UX issue

  - type: checkboxes
    id: security-related
    attributes:
      label: 🔒 Security Related
      options:
        - label: This bug might be security-related

## Description

Describe the bug clearly and concisely.

## Steps to reproduce

1. Go to ...
2. Click ...
3. See error ...

## Expected behavior

What did you expect to happen?

## Screenshots or logs

Paste relevant console logs or screenshots.

## Environment

- OS/Browser:
- App version/commit:

## Additional context

- Auth mode used: PKCE | Device Flow
- Was a GitHub OAuth redirect override used? yes/no
- Any proxy settings involved (dev proxy /\_\_gh/\*)?
