name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check (strict, if TS present)
        run: |
          if npm run -s typecheck --if-present; then
            echo "Ran project typecheck script"
          else
            npx -y typescript tsc -p tsconfig.json --noEmit || true
          fi

      - name: Lint (if present)
        run: npm run lint --if-present

      - name: Run unit tests (if present)
        run: npm test --if-present

      - name: Build
        run: npm run build --if-present

      - name: Upload build artifact (optional)
        if: ${{ success() && hashFiles('dist/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: build-dist
          path: |
            dist/**
            build/**
