name: E2E

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - 'tests/e2e/**'
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
  schedule:
    - cron: '0 2 * * *' # nightly at 02:00 UTC

permissions:
  contents: read

concurrency:
  group: e2e-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  playwright:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        uses: microsoft/playwright-github-action@v1

      - name: Run Playwright tests
        run: npm run e2e

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            playwright-report/**
            test-results/**
          if-no-files-found: ignore

      - name: Add report note to job summary
        if: always()
        run: |
          echo "E2E report artifacts uploaded as 'playwright-report'." >> $GITHUB_STEP_SUMMARY
