name: Seed Labels

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Seed labels from JSON
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          jq -c '.[]' .github/docs/LABELS.json | while read -r label; do
            name=$(echo "$label" | jq -r '.name')
            color=$(echo "$label" | jq -r '.color')
            description=$(echo "$label" | jq -r '.description')
            echo "Seeding label: $name"
            # Try update; if 404 then create
            code=$(curl -s -o /dev/null -w "%{http_code}" \
              -X PATCH \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/${{ github.repository }}/labels/$(printf %s "$name" | jq -s -R -r @uri) \
              -d "{\"new_name\": \"$name\", \"color\": \"$color\", \"description\": \"$description\"}")
            if [ "$code" = "404" ]; then
              curl -s \
                -X POST \
                -H "Authorization: Bearer $GITHUB_TOKEN" \
                -H "Accept: application/vnd.github+json" \
                https://api.github.com/repos/${{ github.repository }}/labels \
                -d "{\"name\": \"$name\", \"color\": \"$color\", \"description\": \"$description\"}"
            fi
          done

      - name: Summary
        run: echo "Labels seeded from .github/docs/LABELS.json" >> $GITHUB_STEP_SUMMARY
